### ISSUE TITLE
Issues arising in connection with the operation

### ISSUE THREAD

**Issue by tuduiduichen** [Farhamdur/CGBA#1]
Hello, I am very interested in what you are researching, but there is a problem during running your program：
 Traceback (most recent call last) 
  File "F:\PycharmProjects\CGBA\Non_targeted_attack.py", line 147, in <module>
    x_adv, n_query, norms = attack.Attack()
  File "F:\PycharmProjects\CGBA\proposed_attack.py", line 249, in Attack
    x_adv, qs = self.go_to_boundary_CGBA_H(self.src_img, grad_oi, x_b)
  File "F:\PycharmProjects\CGBA\proposed_attack.py", line 137, in go_to_boundary_CGBA_H
    m = (torch.sin(theta)*torch.cos(theta/(pow(2, num_calls)))/torch.sin(theta/(pow(2, num_calls)))-torch.cos(theta)).item()
RuntimeError: Overflow when unpacking long，
 can you suggest how to fix it?

**Comment by pijiawei** [comment]
I have the same problem. Did you overcome it?

**Comment by pijiawei** [comment]
> Hello, I am very interested in what you are researching, but there is a problem during running your program： Traceback (most recent call last) File "F:\PycharmProjects\CGBA\Non_targeted_attack.py", line 147, in x_adv, n_query, norms = attack.Attack() File "F:\PycharmProjects\CGBA\proposed_attack.py", line 249, in Attack x_adv, qs = self.go_to_boundary_CGBA_H(self.src_img, grad_oi, x_b) File "F:\PycharmProjects\CGBA\proposed_attack.py", line 137, in go_to_boundary_CGBA_H m = (torch.sin(theta)*torch.cos(theta/(pow(2, num_calls)))/torch.sin(theta/(pow(2, num_calls)))-torch.cos(theta)).item() RuntimeError: Overflow when unpacking long， can you suggest how to fix it?

I have the same problem. Did you overcome it?

**Comment by KevinamdKim** [comment]
I also have this problem, would anyone tell me how to overcome it ?
Sincerely, 
Kevin

**Comment by tuduiduichen** [comment]
I'm sorry, but this is a problem I can't solve either. I suspect the code is inherently faulty




魏琛
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Farhamdur/CGBA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月28日(星期天) 中午1:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Farhamdur/CGBA] Issues arising in connection with the operation (Issue #1)





 
I also have this problem, would anyone tell me how to overcome it ?
 Sincerely,
 Kevin

**Comment by Farhamdur** [comment]
Hi, I am really sorry for the delay in response. I have made a small change in lines 144-145. I hope this will resolve the problem.

**Comment by KevinamdKim** [comment]
Thank you so much for fixing this! I really appreciate your quick response and effort to resolve the issue.
Have a nice day.
Sincerely, 
Kevin
